### ISSUE TITLE
About jpeg and future development of NFT marker creator

### ISSUE THREAD

**Issue by kalwalt** [Carnaux/NFT-Marker-Creator#6] opened 2019-09-23 21:14 UTC
We continue here the discussion started on my PR for NFT https://github.com/kalwalt/jsartoolkit5/pull/2#issuecomment-534261520
@Carnaux  we can leave here our thoughts and solutions for the problem.

**Comment by Carnaux** [comment] 2019-09-23 21:42
To generate the marker files is needed some information about the image:

 - Jpeg image
    - UInt8 Pixel Color Array
    - DPI
    - Width & Height
    - Number of Channels

The function "readImageFromFile" get all the information and set a struct and then other functions can generate the marker files.

Using an HTML input gives only the Uint8 array, the width, and height. I tried setting a placeholder DPI, but it didn't work. I was trying to generate a new jpeg file and store it in the MEMFS and then read it "locally" with the GenTexData.c, so I wouldn't need to change the original code from the unity artoolkit.

**Comment by kalwalt** [comment] 2019-09-24 21:23
Thank you @Carnaux i will look into it when i have a bit of time.

**Comment by Carnaux** [comment] 2019-11-16 14:51
@ThorstenBux Can you help me understand better the marker generation?

**Comment by ThorstenBux** [comment] 2019-11-17 19:10
I can try :). What are your questions?

**Comment by Carnaux** [comment] 2019-11-18 00:37
I solved most of my questions working today :smiley:, I'm generating the iset and fset files, but they don't work, they have drastically different file size than the generated by the genTexData.exe.

**Comment by nicolocarpignoli** [comment] 2019-11-18 07:57
well, that's a great progress :) good luck, as soon as I will have time I will help you

**Comment by kalwalt** [comment] 2019-11-19 17:48
> I solved most of my questions working today , I'm generating the iset and fset files, but they don't work, they have drastically different file size than the generated by the genTexData.exe.

That really strange @Carnaux  but as said Nicolo a great progress!

**Comment by Carnaux** [comment] 2019-11-30 23:45
Just to document one of my attempts:

I tried to execute the genTexData.exe directly in node.js. If you don't pass a file as parameter the expected error message appears, so it runs and does "console.log", but when I pass the path for the file it won't show any sign that it is running.

What the current code can do:
- Execute the genTexData.exe
- Get image via input( It is possible to get a temporary file and get its path, also possible to use the EXIF.js to get dpi, resolution, and color space)

I think that the .exe waiting for input for DPI is getting the code stuck. I tested with a simple hello world in c++ that just outputs and the code worked, when I added an input it got stuck too. A possible solution is the use of child_process.spawn().

If the input problem gets solved, the data got by EXIF.js can create default values for the inputs of the .exe.

**Comment by nicolocarpignoli** [comment] 2019-12-02 13:23
@Carnaux  I think that if you can come up with specific questions and maybe an online example to try (not mandatory) you can ask to Thorsten. He's very will to help. Just come up with some questions here and I will see to make it happen.

**Comment by Carnaux** [comment] 2019-12-04 08:13
Good news!! I found what is making the files with the incorrect content. It is this snippet:

```c
// Decide how many levels we need.
    if (dpiMin == dpiMax) {
        dpi_num = 1;
    } else {
        dpiWork = dpiMin;
        for( i = 1;; i++ ) {
            dpiWork *= powf(2.0f, 1.0f/3.0f); // *= 1.25992104989487
            if( dpiWork >= dpiMax*0.95f ) {
                break;
            }
        }
        dpi_num = i + 1;
    }
```
But I have no idea why. When the `dpiMax` is 220, the `dpi_num` should be 19, in the next part of the code, it uses `dpi_num` as control, and it works fine, but when i try to console.log it, it shows as 0.

**Comment by Carnaux** [comment] 2019-12-07 21:28
Update: I posted about an error dpi_num, but it was a typo error, and it was solved. 

I think I figured out what was the deal. The way I was passing the pixel data as a parameter was wrong, solving that made the generation almost equal to the genTexData.exe, all logs are being shown, and all generation steps are seen to be working. But I noticed that the files still different sizes so they don't work with the NFT example, I believe it is the ARUint8 pixel array data structure, the feature extraction doesn't generate the correct values. @ThorstenBux, I saw in a [forum](https://stackoverflow.com/questions/23666247/artoolkit-using-a-still-image) that the ARUint8 pixel structure changes depending on the SO, it apply in this case too? 


PS: Now all the steps of the marker generation work, but it takes 25 minutes to finish. The code was updated, so anyone can test the generation times.

**Comment by kalwalt** [comment] 2019-12-08 08:41
I will look at for the ARUint8 issue.
25 minutes It Is a huge time...

**Comment by Carnaux** [comment] 2019-12-08 18:32
I developed a node app too, that uses the same markerCreator.min.js as the browser version(the current one), just to test generation times.

###The results:
genTexData.exe: 3 min
Node app: 13 min
Browser version: 25 min

### Some differences:
#### genTexData.exe:
<img src="https://user-images.githubusercontent.com/20483373/70393847-74fdc680-19cd-11ea-8a4e-835330fb4a18.png" width="300" height="auto">

#### Node app:
<img src="https://user-images.githubusercontent.com/20483373/70393848-74fdc680-19cd-11ea-81f8-40b2d1f1d933.png" width="300" height="auto">

The values of filtered features are all slightly higher, but it doesn't log feature coordinates for high DPI values, only for 75 or below. Currently, it is faster than the browser, but I don't know how it will behave when it is hosted.

#### Browser:
<img src="https://user-images.githubusercontent.com/20483373/70393849-74fdc680-19cd-11ea-9a76-ba01bf29421a.png" width="300" height="auto">

The extracted and filtered values aren't correct, but it logs all coordinates for all DPIs.

**Comment by nicolocarpignoli** [comment] 2019-12-09 08:15
Having wrong/few features could be the cause for the non-recognisation on Web.

**Comment by nicolocarpignoli** [comment] 2019-12-10 10:47
@Carnaux 

I think that our 'first' aim was to make it work with Web technologies, but maybe this computation is too heavy for the browser.
In my opinion, it will be great to make it work on node, for example. It will be JS code and runnable on EVERY machine, windows or linux or mac.
So it will be a great improvement from current state-of-the-art, that works only on windows.

I think we have to focus on make it work on node environment, and then, eventually in the future, port it also on the browsers.

But for a lot (maybe every) use case, to generate the descriptors 'offline', and then load them on the web, will be enough.

**Comment by nicolocarpignoli** [comment] 2019-12-10 10:47
If you agree with me, you can focus your efforts on experiments/debug with node version only, like you did on your last post

**Comment by kalwalt** [comment] 2019-12-10 13:12
@Carnaux yes maybe a node version will be also fine and easier to develop. @nicolocarpignoli i can make my own Nft markers also under linux, but you need to build the artoolkitx project and this can be a little cumbersome to insall all the necessary dependencies, so in the scenario of a "normal" user it's a kind of blocking thing, better a lot an alternative app that can run on every OS...

**Comment by Carnaux** [comment] 2019-12-10 14:18
Yeah, I agree. I'm building a new node app, and when it is finished I will reorganize the repository with the main app and other branch to the NftMarkerCreator.min.js build.

**Comment by Carnaux** [comment] 2019-12-10 15:56
Done, the app is on the master branch, you guys can test it. But I still stuck at the feature extraction, I tested changing the order of the RGB pixel array, but still the same as I said, the node app only logs feature coordinates for low dpi values.

**Comment by Carnaux** [comment] 2019-12-12 20:08
Finally!!!! With this last commit, the code works, you now can generate custom NFT Markers!!!! 🎉 Please, test and report any errors or bugs! @kalwalt @nicolocarpignoli

**Comment by ThorstenBux** [comment] 2019-12-12 20:17
I've tested and it is running with other jpg files as well. but I can't see any output files .fset .iset that are created. I've deleted the existing ones added a new jpeg to input. It runs with this output
```
[info] Name = [info] first = 70
[info] Filename: asa
[info] --
Generator started at 2019-12-13 09:15:42 +1300
[info] MAX_THRESH  = 0.900000
[info] MIN_THRESH  = 0.550000
[info] SD_THRESH   = 8.000000
[info] SURF_FEATURE = 100
[info]  min allow 3.733000.
[info] Image DPI (1): 3.733000
[info] Image DPI (2): 4.703285
[info] Image DPI (3): 5.925768
[info] Image DPI (4): 7.466000
[info] Image DPI (5): 9.406571
[info] Image DPI (6): 11.851537
[info] Image DPI (7): 14.932002
[info] Image DPI (8): 18.813144
[info] Image DPI (9): 23.703076
[info] Image DPI (10): 29.864005
[info] Image DPI (11): 37.626289
[info] Image DPI (12): 47.406155
[info] Image DPI (13): 59.728014
[info] Image DPI (14): 75.252583
[info] Image DPI (15): 94.812315
[info] Image DPI (16): 119.456034
[info] Image DPI (17): 150.000000
[info] Generating ImageSet...
[info]    (Source image xsize=1500, ysize=1125, channels=3, dpi=150.0).
[info]   Done.
[info] Saving to asa.iset...
[info]   Done.
[info] Generating FeatureList...
[info] Start for 150.000000 dpi image.
[info] p: 6575032
[info]          ImageSize = 1687500[pixel]
[info] Extracted features =   58037[pixel]
[info]  Filtered features =   33837[pixel]
```
But does not create output files

**Comment by Carnaux** [comment] 2019-12-12 20:23
The process finishes? On my PC it took around 14 min to generate.

**Comment by ThorstenBux** [comment] 2019-12-12 20:25
It looks like it gets stuck because of this `does not contain embedded resolution data, and no resolution specified on command-line.`

**Comment by Carnaux** [comment] 2019-12-12 20:33
Weird, that log is in a function that should not be called. Can you send me the image that you are using?

**Comment by ThorstenBux** [comment] 2019-12-12 20:33
Edited the jpeg now I get
`TypeError: Cannot read property '0' of undefined`

**Comment by ThorstenBux** [comment] 2019-12-12 20:33
Sorry that log is out of the c version of the tool :)
I build that and ran it there.

**Comment by ThorstenBux** [comment] 2019-12-12 20:33
Image on the way

**Comment by ThorstenBux** [comment] 2019-12-12 20:34
https://drive.google.com/file/d/1cs-1n7njiJ4rnnrHTrNjyBolYvqxD58H/view?usp=sharing

**Comment by ThorstenBux** [comment] 2019-12-12 20:35
(I hope google doesn't change the file)

**Comment by ThorstenBux** [comment] 2019-12-12 20:44
Ok, got it now. The link above: That image fails for some reason I don't understand.
I've reverted back to the previous image and waited longer it does work, it just takes a while.

**Comment by Carnaux** [comment] 2019-12-12 20:50
It is the jpeg decoder, I will add this to a to-do list for a future update.

**Comment by Carnaux** [comment] 2019-12-12 21:14
One thing I realized: The images I was using for testing were all 1600 < in width and height, so they were big images. Small images are much faster to generate, but I believe that it has few details for the feature extraction.

**Comment by kalwalt** [comment] 2019-12-12 21:28
@Carnaux @ThorstenBux I will test now!

**Comment by kalwalt** [comment] 2019-12-12 21:45
:tada:  Yesss, it works !! :tada:  see the [log](https://gist.github.com/kalwalt/eb5865b3804a54d93187b931dd8326e2)

**Comment by kalwalt** [comment] 2019-12-12 21:48
Tested with this my image https://www.kalwaltart.com/assets/images/uploads/cubist_dragon.jpg i used for my AR made with **Artivive** read this [article](https://www.kalwaltart.com/blog/2019/01/30/artivive-cubist-dragon-my-free-interactive-artwork/)

**Comment by nicolocarpignoli** [comment] 2019-12-12 23:32
Hi!

I tried on macbook pro. It finishes in ~10-15seconds but no descriptors generated.
I got those warnings (although they're on stderr, to me they look like errors):

```

stderr: /Users/nicolo/libjpeg-for-jsartoolkit5/jdhuff.c:454:13: warning: shifting a negative signed value is undefined [-Wshift-negative-value]
  { 0, ((-1)<<1) + 1, ((-1)<<2) + 1, ((-1)<<3) + 1, ((-1)<<4) + 1,
        ~~~~^
/Users/nicolo/libjpeg-for-jsartoolkit5/jdhuff.c:454:28: warning: shifting a negative signed value is undefined [-Wshift-negative-value]
  { 0, ((-1)<<1) + 1, ((-1)<<2) + 1, ((-1)<<3) + 1, ((-1)<<4) + 1,
                       ~~~~^
/Users/nicolo/libjpeg-for-jsartoolkit5/jdhuff.c:454:43: warning: shifting a negative signed value is undefined [-Wshift-negative-value]
  { 0, ((-1)<<1) + 1, ((-1)<<2) + 1, ((-1)<<3) + 1, ((-1)<<4) + 1,
                                      ~~~~^
/Users/nicolo/libjpeg-for-jsartoolkit5/jdhuff.c:454:58: warning: shifting a negative signed value is undefined [-Wshift-negative-value]
  { 0, ((-1)<<1) + 1, ((-1)<<2) + 1, ((-1)<<3) + 1, ((-1)<<4) + 1,
                                                     ~~~~^
/Users/nicolo/libjpeg-for-jsartoolkit5/jdhuff.c:455:10: warning: shifting a negative signed value is undefined [-Wshift-negative-value]
    ((-1)<<5) + 1, ((-1)<<6) + 1, ((-1)<<7) + 1, ((-1)<<8) + 1,
     ~~~~^
/Users/nicolo/libjpeg-for-jsartoolkit5/jdhuff.c:455:25: warning: shifting a negative signed value is undefined [-Wshift-negative-value]
    ((-1)<<5) + 1, ((-1)<<6) + 1, ((-1)<<7) + 1, ((-1)<<8) + 1,
                    ~~~~^
/Users/nicolo/libjpeg-for-jsartoolkit5/jdhuff.c:455:40: warning: shifting a negative signed value is undefined [-Wshift-negative-value]
    ((-1)<<5) + 1, ((-1)<<6) + 1, ((-1)<<7) + 1, ((-1)<<8) + 1,
                                   ~~~~^
/Users/nicolo/libjpeg-for-jsartoolkit5/jdhuff.c:455:55: warning: shifting a negative signed value is undefined [-Wshift-negative-value]
    ((-1)<<5) + 1, ((-1)<<6) + 1, ((-1)<<7) + 1, ((-1)<<8) + 1,
                                                  ~~~~^
/Users/nicolo/libjpeg-for-jsartoolkit5/jdhuff.c:456:10: warning: shifting a negative signed value is undefined [-Wshift-negative-value]
    ((-1)<<9) + 1, ((-1)<<10) + 1, ((-1)<<11) + 1, ((-1)<<12) + 1,
     ~~~~^
/Users/nicolo/libjpeg-for-jsartoolkit5/jdhuff.c:456:25: warning: shifting a negative signed value is undefined [-Wshift-negative-value]
    ((-1)<<9) + 1, ((-1)<<10) + 1, ((-1)<<11) + 1, ((-1)<<12) + 1,
                    ~~~~^
/Users/nicolo/libjpeg-for-jsartoolkit5/jdhuff.c:456:41: warning: shifting a negative signed value is undefined [-Wshift-negative-value]
    ((-1)<<9) + 1, ((-1)<<10) + 1, ((-1)<<11) + 1, ((-1)<<12) + 1,
                                    ~~~~^
/Users/nicolo/libjpeg-for-jsartoolkit5/jdhuff.c:456:57: warning: shifting a negative signed value is undefined [-Wshift-negative-value]
    ((-1)<<9) + 1, ((-1)<<10) + 1, ((-1)<<11) + 1, ((-1)<<12) + 1,
                                                    ~~~~^
/Users/nicolo/libjpeg-for-jsartoolkit5/jdhuff.c:457:10: warning: shifting a negative signed value is undefined [-Wshift-negative-value]
    ((-1)<<13) + 1, ((-1)<<14) + 1, ((-1)<<15) + 1 };
     ~~~~^
/Users/nicolo/libjpeg-for-jsartoolkit5/jdhuff.c:457:26: warning: shifting a negative signed value is undefined [-Wshift-negative-value]
    ((-1)<<13) + 1, ((-1)<<14) + 1, ((-1)<<15) + 1 };
                     ~~~~^
/Users/nicolo/libjpeg-for-jsartoolkit5/jdhuff.c:457:42: warning: shifting a negative signed value is undefined [-Wshift-negative-value]
    ((-1)<<13) + 1, ((-1)<<14) + 1, ((-1)<<15) + 1 };
                                     ~~~~^
15 warnings generated.
/Users/nicolo/libjpeg-for-jsartoolkit5/jdphuff.c:214:13: warning: shifting a negative signed value is undefined [-Wshift-negative-value]
  { 0, ((-1)<<1) + 1, ((-1)<<2) + 1, ((-1)<<3) + 1, ((-1)<<4) + 1,
        ~~~~^
/Users/nicolo/libjpeg-for-jsartoolkit5/jdphuff.c:214:28: warning: shifting a negative signed value is undefined [-Wshift-negative-value]
  { 0, ((-1)<<1) + 1, ((-1)<<2) + 1, ((-1)<<3) + 1, ((-1)<<4) + 1,
                       ~~~~^
/Users/nicolo/libjpeg-for-jsartoolkit5/jdphuff.c:214:43: warning: shifting a negative signed value is undefined [-Wshift-negative-value]
  { 0, ((-1)<<1) + 1, ((-1)<<2) + 1, ((-1)<<3) + 1, ((-1)<<4) + 1,
                                      ~~~~^
/Users/nicolo/libjpeg-for-jsartoolkit5/jdphuff.c:214:58: warning: shifting a negative signed value is undefined [-Wshift-negative-value]
  { 0, ((-1)<<1) + 1, ((-1)<<2) + 1, ((-1)<<3) + 1, ((-1)<<4) + 1,
                                                     ~~~~^
/Users/nicolo/libjpeg-for-jsartoolkit5/jdphuff.c:215:10: warning: shifting a negative signed value is undefined [-Wshift-negative-value]
    ((-1)<<5) + 1, ((-1)<<6) + 1, ((-1)<<7) + 1, ((-1)<<8) + 1,
     ~~~~^
/Users/nicolo/libjpeg-for-jsartoolkit5/jdphuff.c:215:25: warning: shifting a negative signed value is undefined [-Wshift-negative-value]
    ((-1)<<5) + 1, ((-1)<<6) + 1, ((-1)<<7) + 1, ((-1)<<8) + 1,
                    ~~~~^
/Users/nicolo/libjpeg-for-jsartoolkit5/jdphuff.c:215:40: warning: shifting a negative signed value is undefined [-Wshift-negative-value]
    ((-1)<<5) + 1, ((-1)<<6) + 1, ((-1)<<7) + 1, ((-1)<<8) + 1,
                                   ~~~~^
/Users/nicolo/libjpeg-for-jsartoolkit5/jdphuff.c:215:55: warning: shifting a negative signed value is undefined [-Wshift-negative-value]
    ((-1)<<5) + 1, ((-1)<<6) + 1, ((-1)<<7) + 1, ((-1)<<8) + 1,
                                                  ~~~~^
/Users/nicolo/libjpeg-for-jsartoolkit5/jdphuff.c:216:10: warning: shifting a negative signed value is undefined [-Wshift-negative-value]
    ((-1)<<9) + 1, ((-1)<<10) + 1, ((-1)<<11) + 1, ((-1)<<12) + 1,
     ~~~~^
/Users/nicolo/libjpeg-for-jsartoolkit5/jdphuff.c:216:25: warning: shifting a negative signed value is undefined [-Wshift-negative-value]
    ((-1)<<9) + 1, ((-1)<<10) + 1, ((-1)<<11) + 1, ((-1)<<12) + 1,
                    ~~~~^
/Users/nicolo/libjpeg-for-jsartoolkit5/jdphuff.c:216:41: warning: shifting a negative signed value is undefined [-Wshift-negative-value]
    ((-1)<<9) + 1, ((-1)<<10) + 1, ((-1)<<11) + 1, ((-1)<<12) + 1,
                                    ~~~~^
/Users/nicolo/libjpeg-for-jsartoolkit5/jdphuff.c:216:57: warning: shifting a negative signed value is undefined [-Wshift-negative-value]
    ((-1)<<9) + 1, ((-1)<<10) + 1, ((-1)<<11) + 1, ((-1)<<12) + 1,
                                                    ~~~~^
/Users/nicolo/libjpeg-for-jsartoolkit5/jdphuff.c:217:10: warning: shifting a negative signed value is undefined [-Wshift-negative-value]
    ((-1)<<13) + 1, ((-1)<<14) + 1, ((-1)<<15) + 1 };
     ~~~~^
/Users/nicolo/libjpeg-for-jsartoolkit5/jdphuff.c:217:26: warning: shifting a negative signed value is undefined [-Wshift-negative-value]
    ((-1)<<13) + 1, ((-1)<<14) + 1, ((-1)<<15) + 1 };
                     ~~~~^
/Users/nicolo/libjpeg-for-jsartoolkit5/jdphuff.c:217:42: warning: shifting a negative signed value is undefined [-Wshift-negative-value]
    ((-1)<<13) + 1, ((-1)<<14) + 1, ((-1)<<15) + 1 };
                                     ~~~~^
15 warnings generated.


Running command: /usr/local/Cellar/emscripten/1.38.44/bin/emcc -I/Users/nicolo/artoolkit5/include -I/Users/nicolo/NFT-Marker-Creator/build/ -I/Users/nicolo/NFT-Marker-Creator/emscripten/ -I/Users/nicolo/artoolkit5/lib/SRC/KPM/FreakMatcher -I/Users/nicolo/libjpeg  /Users/nicolo/NFT-Marker-Creator/build/libar.bc /Users/nicolo/NFT-Marker-Creator/build/libjpeg.bc /Users/nicolo/NFT-Marker-Creator/emscripten/assemble.c -s EXPORTED_FUNCTIONS=["_createImageSet"] -s EXTRA_EXPORTED_RUNTIME_METHODS=["FS"]  -O3  -Wno-warn-absolute-paths  -s TOTAL_MEMORY=268435456  -s ALLOW_MEMORY_GROWTH=1  -s USE_ZLIB=1 -s ERROR_ON_UNDEFINED_SYMBOLS=0 -s ASSERTIONS=1 --memory-init-file 0  -s FORCE_FILESYSTEM=1 -s WASM=0   -D HAVE_NFT  -o /Users/nicolo/NFT-Marker-Creator/build/NftMarkerCreator.min.js 

stderr: shared:WARNING: not all asm.js optimizations are possible with ALLOW_MEMORY_GROWTH, disabling those. [-Walmost-asm]

Jobs completed
```

any idea?

**Comment by nicolocarpignoli** [comment] 2019-12-12 23:32
Tried with thorsten image above

**Comment by nicolocarpignoli** [comment] 2019-12-12 23:36
which version of emscripten do you have guys?
Mine is 1.38.44

**Comment by Carnaux** [comment] 2019-12-12 23:47
I always got those warnings about libjpeg, but it never failed the build 😕 

Yes, it is outdated, sorry, I will change it, is just in case your libjpeg folder is in other place.

My version is 1.39.4

**Comment by nicolocarpignoli** [comment] 2019-12-12 23:49
the build does not failed actually. I see that the 'output' directory is not present. I have manually created it but does not work either

**Comment by Carnaux** [comment] 2019-12-12 23:50
The dev branch just generates the NftMarkerCreator.min.js, to generate the marker itself you have to use the master

**Comment by nicolocarpignoli** [comment] 2019-12-12 23:51
Yes, I was just to write it! I didn't understand that!

**Comment by nicolocarpignoli** [comment] 2019-12-13 00:02
So the complete flux, as for now, should be:

* checkout on dev
* follow readme (apart from point 4)
* .min.js file is generated
* keep that file
* checkout on master
* replace .min.js with copied one
* run node app.js


I got error with this flow.

```
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
```

Also, I was able to create .iset files using the Editor.html from dev branch but they did not seem to work.

**Comment by Carnaux** [comment] 2019-12-13 00:11
That flow is just if you want to make some changes to the min.js, the master branch is ready to use. I'm making some changes in the dev branch, making it cleaner, the html editor is discontinued.

**Comment by Carnaux** [comment] 2019-12-13 00:41
I made the changes in the dev branch, it is cleaner now. 

One thing I've been thinking is to merge the .iset, .fset and .fset3 files in just one maybe is more practical? What do you guys think? @kalwalt @ThorstenBux @nicolocarpignoli

**Comment by jamess922** [comment] 2019-12-13 03:42
Hi I tried and it's come out with this 
`C:\Users\Cai-TP>node app.js
The EXIF info of this image is empty or it does not exist. Do you want to inform its properties manually?[y/n]`

**Comment by Carnaux** [comment] 2019-12-13 03:52
You type "y" and press enter after that will have other dialogs, for Width and Height of the image, and for DPI if you want to inform one(or just press enter, the code will use 72 as default)

**Comment by jamess922** [comment] 2019-12-13 04:38
Thank you It's working ,get the files

**Comment by nicolocarpignoli** [comment] 2019-12-13 08:50
it works on master branch! Great!!

As next step I would suggest to automate it even more:

* detect width/height of the image
* detect black&white or colored image (to automatically set NC=1 or NC=3)
* detect DPI 

For each of them, if can't retrieve, fallback to a default.

I don't know if this is all possible but should be great.

Anyway, your idea to create a basic HTML page as generator was great.
This because people used to use a marker generator for fiducial marker on AR.js 
https://jeromeetienne.github.io/AR.js/three.js/examples/marker-training/examples/generator.html

Something very similar to create NFT images will do, like:

* upload your image
* create button
* if needed, ask the user (prompt) for data specified above (dpi, w/h and black&white or coloured image).

What do you think?

**Comment by nicolocarpignoli** [comment] 2019-12-13 08:51
Next weeks I will be a bit busy to try to port NFT jsartoolkit5 on AR.js but I will always provide support for this, and when I will be more free even 'development' support :)

**Comment by kalwalt** [comment] 2019-12-13 13:11
I think a node app is the most reasonable solution at the moment, much easier than having to clone **artoolkitx**, install all the dependencies (what a panic!) and compile the C++ project . Above all if you are not an experieced C++ this is discouraging...

**Comment by Carnaux** [comment] 2019-12-13 13:51
@nicolocarpignoli the node app already does the automation, it only asks to input info if the decoder can't get the EXIF info. But the c++ code has some advanced inputs, e.g the precision of the feature extraction, I will add those options later.

I just uploaded a simple page with the browser version: https://carnaux.github.io/NFT-Marker-Creator-Web/

It is not faster, but for small images is more practical.

**Comment by kalwalt** [comment] 2019-12-13 14:24
@Carnaux i tried with the browser version, yes it seems it takes longer to generate the data set...

**Comment by Carnaux** [comment] 2019-12-14 01:49
I just added PNG support for the node app!! It works with grayscale and RGB/RGBA images.

**Comment by kalwalt** [comment] 2019-12-14 09:06
> I just added PNG support for the node app!! It works with grayscale and RGB/RGBA images.
> 
> Edit: Also added to the browser version!

Great @Carnaux !! Thank you!

**Comment by nicolocarpignoli** [comment] 2019-12-15 12:20
@Carnaux does it make sense to close this PR and work directly on specific features, that solves specific issue?

**Comment by Carnaux** [comment] 2019-12-15 19:00
Yes, this was just for general conversation.

**Closed** 2019-12-15 19:03 UTC
